### ISSUE TITLE
Old version download pop-up

### ISSUE THREAD

**Issue by alptezbasaran** [MrBean355/admiralbulldog-sounds#18]
After updating to 1.9.9 the app pop-up update for 1.9.1 then shows 1.9.10

It should check nightly version. I believe current check is from release version. So even though you update to a nightly version it checks all the updates after that release.

**Comment by MrBean355** [comment]
Hello @alptezbasaran 
There are different version numbers for the app and for the mod.
Currently the latest app version is 1.9.1 and latest mod version is 1.9.10.
The latest version of the app can be found [here](https://github.com/MrBean355/admiralbulldog-sounds/releases).
The latest version of the mod can be found [here](https://github.com/MrBean355/admiralbulldog-mod/releases).
The mod is updated regularly, because it needs to be updated to be compatible with the latest Dota update.
Hopefully this clears things up?

**Comment by alptezbasaran** [comment]
I downloaded 1.9.9
The pop-up suggests I should downgrade to 1.9.1 then suggests I should upgrade to 1.9.10

**Comment by MrBean355** [comment]
There is no version 1.9.9, where did you find it?

**Comment by alptezbasaran** [comment]
That seems to be mod version
What you are saying 1.9.1 is app version

Mod version is 1.9.10
Quite confusing to be honest. But no issue if you put it that way. You can close this but I would go for a different identifier for a mod version like alphabet or Roman numerals

**Comment by MrBean355** [comment]
Sorry, the version names are a bit unfortunate at the moment. Apologies for the confusion.
