### ISSUE TITLE
2 Questions. Remove old hero icons and custom sounds. 

### ISSUE THREAD

**Issue by therealPelo** [MrBean355/admiralbulldog-sounds#21]
First, is there a way to remove the old hero icons? I prefer the normal ones. 

Second, is it possible to add my own sound bytes or change ones already in there? Like the CM ult for example. 

Great mod overall!

**Comment by MrBean355** [comment]
Hey @therealPelo 

Unfortunately Dota mods are very difficult to customise, just because of how they work.
I'm trying to figure out how I can allow people to choose what parts of the mod they want, but it's not possible at the moment.
If you'd like to customise it at the moment, you'll need to make your own mod sadly.

Not the answer you were hoping for, but it's just how modding works, sorry!

**Comment by MrBean355** [comment]
Closing for now, feel free to add more comments!
