### ISSUE TITLE
Add custom sounds?

### ISSUE THREAD

**Issue by zopad** [MrBean355/admiralbulldog-sounds#22]
Is there any way to add custom, local sound files?

The only way I could imagine it currently:

- Add mp3s to/sounds folder
- Manually add the filename entries to the config.json

Would this work?
Is there any other way?

Thanks :)

**Comment by MrBean355** [comment]
Hey @zopad 

I've been thinking about this for a while, but it isn't high priority. It gets tricky when you want to play these custom sounds through Discord. I'll have to implement some kind of log in method so the sounds can be uploaded for use with Discord.

> The only way I could imagine it currently:
> - Add mp3s to/sounds folder
> - Manually add the filename entries to the config.json

This will work fine, but you won't be able to play these sounds through Discord, since the bot doesn't know about them.

**Comment by zopad** [comment]
Some kind of upload would be nice indeed. But I understand it's not trivial.
Thanks for the answer!
